apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    name: flask
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flask
  template:
    metadata:
      labels:
        name: flask
    spec:
      containers:
      - image: melinaci/flaskapp
        name: flaskapp
        ports:
        - containerPort: 6000