version: '3'
services:
  # Frontend service running on port 8000
  frontend:
    build: ./microservice-demo-frontend-master
    ports:
      - "8000:8000"
  # Node service running on port 4000
  node:
    build: ./microservice-demo-node-master
    ports:
      - "4000:4000"
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
  # Redis database for node application
  redis:
    image: redis
    container_name: cache
    expose:
        - "6379"
  # API gateway (5000)
  apigateway:
    build: ./microservice-demo-apigateway-master
    ports:
      - "5000:5000"
    environment: 
      - NODE_ENDPOINT=http://node:4000/
      - GO_ENDPOINT=http://go:8080/
      - FLASK_ENDPOINT=http://flask:6000/
  # Flask service (8010)
  flask:
    build: ./microservice-demo-flask-master
    ports:
      - "6000:6000"
  # Go service running on port 8080
  go:
    build: ./microservice-demo-go-master/src
    ports:
      - "8080:8080"