version: '3'
services:
  web:
    build: .
    depends_on:
      - redis
    ports:
      - "8080:5000"
  redis:
    image: redis
    expose:
      - "6379"
    volumes:
      - redis:/data
  node:
    image: nodeapplication
  flask:
    image: flasky
  go:
    image: goapp